#!/usr/bin/env python3
"""
Fan a reference restyle out to every copy of a component (E-25).

A Theme C restyle is written ONCE, against one reference component's class
names, in src/theme/ref/<anything>.css:

    /* @ref src/Components/AddTabs/AddTabs.css */
    html.theme-c .Add-tabs-wrap { ... }
    html.theme-c .Add-tab:hover { ... }

This script finds every stylesheet with the same selector structure as the
reference (see clusters.py --relaxed: the n-th class of one copy IS the n-th
class of every other) and rewrites each class in the selectors to an :is()
list of its counterparts:

    html.theme-c :is(.Add-tabs-wrap,.cic-tabs-wrap,.cio-tabs-wrap,…) { ... }

so one rule styles all the copies. No component file is touched, which is what
keeps the content risk at zero. The result is written to
src/theme/families.css — GENERATED, never edited by hand. Re-run after any
change under src/theme/ref/.

    python3 scripts/theme/fanout.py           # write families.css
    python3 scripts/theme/fanout.py --check   # exit 1 if families.css is stale
"""
import glob, os, re, sys
sys.path.insert(0, os.path.dirname(__file__))
from clusters import signature, CLASS

FRONTEND = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
REF_DIR = os.path.join(FRONTEND, "src", "theme", "ref")
OUT = os.path.join(FRONTEND, "src", "theme", "families.css")
REF = re.compile(r"/\*\s*@ref\s+(\S+)\s*\*/")

def build_clusters():
    by_sig, by_file = {}, {}
    for path in sorted(glob.glob(os.path.join(FRONTEND, "src", "Components", "*", "*.css"))):
        sig, order = signature(open(path, encoding="utf-8", errors="ignore").read(), relaxed=True)
        rel = os.path.relpath(path, FRONTEND)
        by_sig.setdefault(sig, []).append((rel, order))
        by_file[rel] = sig
    return by_sig, by_file

def expand(block, ref_file, by_sig, by_file, report):
    if ref_file not in by_file:
        raise SystemExit(f"@ref {ref_file}: no such stylesheet (path is relative to Frontend/)")
    members = by_sig[by_file[ref_file]]
    ref_order = next(o for f, o in members if f == ref_file)
    alts = {}
    for i, name in enumerate(ref_order):
        seen = []
        for _, order in members:
            if order[i] not in seen: seen.append(order[i])
        alts[name] = seen
    report.append((ref_file, len(members)))

    # rewrite classes only in selector position (text directly before a "{")
    tokens = re.split(r"([{}])", block)
    res = []
    for idx, tok in enumerate(tokens):
        nxt = tokens[idx + 1] if idx + 1 < len(tokens) else ""
        if tok not in "{}" and nxt == "{" and not tok.strip().startswith("@"):
            def sub(m):
                names = alts.get(m.group(1))
                if not names or len(names) == 1: return m.group(0)
                return ":is(" + ",".join("." + n for n in names) + ")"
            tok = CLASS.sub(sub, tok)
        res.append(tok)
    return "".join(res)

def generate():
    by_sig, by_file = build_clusters()
    report, parts = [], []
    for src in sorted(glob.glob(os.path.join(REF_DIR, "*.css"))):
        css = open(src, encoding="utf-8").read()
        pieces = REF.split(css)  # [before, file1, block1, file2, block2…]
        if pieces[0].strip() and not pieces[0].strip().startswith("/*"):
            raise SystemExit(f"{src}: rules before the first /* @ref … */ banner")
        for ref_file, block in zip(pieces[1::2], pieces[2::2]):
            parts.append(f"/* {os.path.basename(src)} — from {ref_file} */\n{expand(block, ref_file, by_sig, by_file, report).strip()}\n")
    header = ("/* GENERATED by scripts/theme/fanout.py from src/theme/ref/*.css — do not edit.\n"
              "   Each rule was written once against a reference component and fanned out to\n"
              "   every copy with the same selector structure. Scoped under html.theme-c. */\n\n")
    return header + "\n".join(parts), report

if __name__ == "__main__":
    text, report = generate()
    if "--check" in sys.argv:
        stale = not os.path.exists(OUT) or open(OUT, encoding="utf-8").read() != text
        print("families.css is", "STALE — run scripts/theme/fanout.py" if stale else "up to date")
        sys.exit(1 if stale else 0)
    open(OUT, "w", encoding="utf-8").write(text)
    for ref_file, n in report:
        print(f"{n:4d} copies  ←  {ref_file}")
    print(f"wrote {os.path.relpath(OUT, FRONTEND)} ({len(text) // 1024} KB)")
