import React from "react";
import "./EsiRetFeatures.css";

const types = [
  {
    number: "01",
    title: "Employee Addition in ESI Portal (New IP Creation)",
    text: "When a new employee joins (and is covered under the ESI threshold), we add them in the ESIC portal as a new INSURED PERSON. Captures: name, DOB, Aadhaar, PAN, Bank account, gender, photograph, family / nominee details, joining date. IP NUMBER (Insurance Number) is generated by the portal — the IP's lifelong identifier for ESI medical + monetary benefits.",
  },
  {
    number: "02",
    title: "Employee Exit Marking in ESI Portal",
    text: "When an employee leaves (resignation / retirement / termination), we mark the EXIT in the ESI portal capturing: last working day + reason for exit. This ensures: no further contributions are computed for the member after exit; the IP can still claim accumulated benefits + transfer membership to next employer; and your monthly contribution ledger is accurate.",
  },
  {
    number: "03",
    title: "Monthly ESI Return Filing (Contribution Upload)",
    text: "The MONTHLY CONTRIBUTION upload on the ESIC portal is the core compliance filing. Generated from your monthly wage register: IP-wise gross wages + Employee 0.75% + Employer 3.25% = Total 4% per IP. We validate every IP's wage data + compute contributions + generate the Contribution Statement in ESIC portal format + upload before the 15th-of-next-month deadline.",
  },
  {
    number: "04",
    title: "ESI Contribution Payment Coordination",
    text: "Once the monthly Contribution is uploaded, the ESIC portal generates a CHALLAN with the total amount payable. We coordinate the payment to ESIC — via Internet Banking (SBI + 60+ empanelled banks) OR NEFT / RTGS using the challan reference. We track payment confirmation + verify the payment is reconciled by ESIC.",
  },
  {
    number: "05",
    title: "Challan Mail to Client",
    text: "Same day as Contribution upload: we EMAIL THE ESI CHALLAN to you along with payment instructions (bank, beneficiary, amount, due date, payment reference). A clear paper-trail in your inbox. Once payment is confirmed, the final paid-challan acknowledgement is also emailed.",
  },
  {
    number: "06",
    title: "Contribution History Mail to Client",
    text: "Monthly: we email you the COMPLETE CONTRIBUTION HISTORY — IP-wise wages + contributions for the month + running totals for the current contribution period (April–September OR October–March) + verification of all IPs' coverage status (active / exited / wage-ceiling-crossed). Clean ledger every month, no surprises at half-year.",
  },
];

const EsiRetFeatures = () => {
  return (
    <section className="opc-features-section">
      <div className="opc-features-container">

        <h2 className="opc-features-title">Types of ESI Returns in India</h2>
        <p className="esiret-features-subtitle">
          ESI Return Filing covers the 7 monthly deliverables we execute for you — the same 7 across all 3 tiers; only the tier varies by employee count.
        </p>

        <div className="opc-features-cards">
          {types.map((type) => (
            <div className="opc-features-card" key={type.number}>
              <div className="opc-features-number">{type.number}</div>
              <h3 className="opc-features-card-title">{type.title}</h3>
              <p className="opc-features-card-text">{type.text}</p>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
};

export default EsiRetFeatures;
