#!/usr/bin/env node
/**
 * Cut a release: bump the product version, write the changelog, tag it.
 *
 * WHY. "Is the fix deployed yet?" had no answer. A production bug was reported
 * whose fix was already on `main`, and nothing identified what the running
 * deploy contained, so the only way to tell was to guess. No git tags existed.
 *
 * THE ROOT package.json IS THE PRODUCT VERSION. `backend/` and `Portal/` carry
 * their own numbers because npm workspaces require them; those describe
 * packages, not the shipped product, and are deliberately NOT kept in sync.
 * Three hand-maintained numbers is exactly how they drifted apart.
 *
 * Usage:
 *   npm run release -- patch|minor|major [--dry]
 *
 * What it does, in order:
 *   1. refuses to run on a dirty tree or off `main` (a release must be
 *      reproducible from a commit anyone can check out)
 *   2. bumps the root version
 *   3. regenerates CHANGELOG.md from Conventional Commits since the last tag
 *   4. commits and creates an ANNOTATED tag (annotated so it carries a date and
 *      author, and is not treated as disposable the way a lightweight one is)
 *
 * PUSHING is opt-in: pass `--publish` to push the tag AND create the GitHub
 * Release carrying this version's notes. Without it the script stops at a local
 * commit + tag for review.
 *
 * A tag alone is not a release. The tag is a pointer only visible to someone
 * with a clone; the Release is the published artifact — it puts the notes where
 * people actually look, and gives a deploy something to name. Tags without
 * releases is the state this repo was in, and it made "what shipped in v1.1.0?"
 * unanswerable without reading git log.
 */
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const sh = (cmd) => execSync(cmd, { encoding: 'utf8' }).trim();
const die = (msg) => { console.error(`✖ ${msg}`); process.exit(1); };

const bump = process.argv[2];
const dry = process.argv.includes('--dry');
const publish = process.argv.includes('--publish');
if (!['patch', 'minor', 'major'].includes(bump)) {
  die('usage: npm run release -- patch|minor|major [--dry] [--publish]');
}

// ── Guards ───────────────────────────────────────────────────────────────────
if (!dry && sh('git status --porcelain')) die('working tree is dirty — commit or stash first');
const branch = sh('git rev-parse --abbrev-ref HEAD');
if (!dry && branch !== 'main') die(`releases are cut from main, not '${branch}'`);

// ── Bump ─────────────────────────────────────────────────────────────────────
const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
const [maj, min, pat] = pkg.version.split('.').map(Number);
const next = bump === 'major' ? `${maj + 1}.0.0`
  : bump === 'minor' ? `${maj}.${min + 1}.0`
  : `${maj}.${min}.${pat + 1}`;
const tag = `v${next}`;

if (sh('git tag').split('\n').includes(tag)) die(`${tag} already exists`);

// ── Changelog ────────────────────────────────────────────────────────────────
const tags = sh('git tag --sort=-v:refname').split('\n').filter(Boolean);
const prev = tags[0] ?? null;
const range = prev ? `${prev}..HEAD` : 'HEAD';
const log = sh(`git log ${range} --no-merges --pretty=format:%s`).split('\n').filter(Boolean);

// Conventional Commits → sections. Anything unparseable still appears, under
// "Other" — a release note that silently drops commits is worse than a messy one.
const SECTIONS = [
  ['feat', 'Features'],
  ['fix', 'Fixes'],
  ['perf', 'Performance'],
  ['refactor', 'Refactoring'],
  ['test', 'Tests'],
  ['docs', 'Documentation'],
  ['content', 'Content'],
  ['chore', 'Chores'],
];
const buckets = new Map(SECTIONS.map(([k]) => [k, []]));
const other = [];
const breaking = [];

for (const line of log) {
  const m = /^(\w+)(\([^)]*\))?(!)?:\s*(.+)$/.exec(line);
  if (!m) { other.push(line); continue; }
  const [, type, scope, bang, subject] = m;
  const entry = `${scope ? `**${scope.slice(1, -1)}**: ` : ''}${subject}`;
  if (bang) breaking.push(entry);
  if (buckets.has(type)) buckets.get(type).push(entry);
  else other.push(line);
}

const today = new Date().toISOString().slice(0, 10);
const out = [`## ${tag} — ${today}`, ''];
if (breaking.length) {
  out.push('### ⚠ BREAKING CHANGES', '');
  breaking.forEach((e) => out.push(`- ${e}`));
  out.push('');
}
for (const [key, title] of SECTIONS) {
  const items = buckets.get(key);
  if (!items.length) continue;
  out.push(`### ${title}`, '');
  items.forEach((e) => out.push(`- ${e}`));
  out.push('');
}
if (other.length) {
  out.push('### Other', '');
  other.forEach((e) => out.push(`- ${e}`));
  out.push('');
}

const HEADER = `# Changelog

All notable changes to Legal Terminus. Generated by \`scripts/release.mjs\` from
Conventional Commits — edit the commits, not this file.

Each released version is an annotated git tag. An installation reports the
version it is running on \`GET /health\`.
`;

const existing = existsSync('CHANGELOG.md')
  ? readFileSync('CHANGELOG.md', 'utf8').replace(HEADER, '').trimStart()
  : '';
const changelog = `${HEADER}\n${out.join('\n')}\n${existing}`.trimEnd() + '\n';

console.log(`\n${tag}  (${log.length} commits since ${prev ?? 'the beginning'})\n`);
console.log(out.join('\n'));

if (dry) { console.log('— dry run, nothing written —'); process.exit(0); }

pkg.version = next;
writeFileSync('package.json', `${JSON.stringify(pkg, null, 2)}\n`);
writeFileSync('CHANGELOG.md', changelog);

execSync('git add package.json CHANGELOG.md');
execSync(`git commit -m "chore(release): ${tag}"`);
execSync(`git tag -a ${tag} -m "${tag}"`);

console.log(`\n✔ committed and tagged ${tag}`);
console.log('  review it, then: git push --follow-tags');
